### ISSUE TITLE
Old Version Requirement Information But Still Works

### ISSUE THREAD

**Issue by imakunee** [Skrelpoid/SuperFastMode#22]
For those wondering, this mod still seems fully functional (at least with quick startup) using BaseMod 3.2.2, ModTheSpire 3.2.0, and SlayTheSpire 09-06-2018. This is in spite of the gap in updates and ModTheSpire's warnings about possible version conflict. Feel free to use it! :)

**Comment by Skrelpoid** [comment]
Hi, I will update the mod so that the version will actually reflect that it is indeed compatible with the current versions of the game and ModTheSpire and BaseMod
