### ISSUE TITLE
noux 999.0.0 gives me an error message

### ISSUE THREAD

**Issue by AvangionQ** [Skrelpoid/SuperFastMode#36]
noux 999.0.0 gives me an error message
says to go yell at the author to fix it
https://i.postimg.cc/hPNK1GvC/Slay-the-Spire-super-fast-mode-error.png

**Comment by Skrelpoid** [comment]
I forgot to mark it as a prerelease, should be fixed, let me know if you still get the same message

**Comment by AvangionQ** [comment]
Uh oh, same error message 😶

**Comment by Skrelpoid** [comment]
Can you check if the issue is fixed now?

**Comment by AvangionQ** [comment]
Working as intended ✅
