### ISSUE TITLE
Possible to disable *all* animations?

### ISSUE THREAD

**Issue by jcmorrow** [Skrelpoid/SuperFastMode#38]
Hi! Thanks for writing this awesome mod! I want to do some machine learning experiments with Slay the Spire and SuperFastMode has been really helpful! In the readme I saw:

> This means that you can still enjoy most Monster and Player Animations at normal speed, while the actual gameplay is lightning fast.

Since I'm playing with an AI I actually don't want *any* animations. Would that be a hard change for me (a software developer with basically no Java experience) to make? Could you provide any guidance on where to get started?

Thanks!

**Comment by Skrelpoid** [comment]
Hi, there's a version intended for AI with no ux features, so it is significantly faster, see https://github.com/Skrelpoid/SuperFastMode/releases/tag/noux999.0.0. You could start from that branch https://github.com/Skrelpoid/SuperFastMode/tree/noux999.0.0 and try to remove all Actions that only render stuff from the Abstract Dungeon.actionManager.
It might even be enough to just remove all WaitAction every frame.

**Comment by jcmorrow** [comment]
This is perfect, thank you! I'll let you know how it goes!
